### ISSUE TITLE
Possibly doesn't work with add-on police cars.

### ISSUE THREAD

**Issue by ToastinYou** [ToastinYou/ToastysCruiseControl#5]

**Comment by nak0604** [comment]
I have just tried this on my fivem server and I can confirm it doesnt work with add-on cars. But I have also noticed that it doesnt really work at all in a way. I have to hold the assigned button down for 5 seconds before it will work. After that the car cant be turned bumped or anything or else it will cancel the cruise control.

**Comment by ToastinYou** [comment]
This project is no longer being worked on.
